services:
  fast-api:
    container_name: cc-backend
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - '.:/app'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: cc-database
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: pg_isready -h localhost -U ${POSTGRES_USER}
      interval: 2s
      timeout: 5s
      retries: 15
    volumes:
      - './docker/postgres/data:/var/lib/postgresql/data'
      - './docker/postgres/conf:/etc/postgresql'
      - './database:/docker-entrypoint-initdb.d'
