services:
  fast-api:
    container_name: cc-backend
    build:
      context: .
    ports:
      - 80:80

  postgres:
    image: postgres:latest
    container_name: cc-database
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - './docker/postgres/data:/var/lib/postgresql/data'
      - './docker/postgres/conf:/etc/postgresql'
      - './database:/docker-entrypoint-initdb.d'